intra/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('users.urls')),
	url(r'^kfet/', include('kfet.urls')),
	url(r'^thuysses/', include('thuysses.urls')),
)

kfet/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('kfet.views',
		url(r'^$', "index", name = 'index_kfet'),
		url(r'^products/$', "products", name = 'products'),
		url(r'^statistics/$', "statistics", name = 'statistics'),
		url(r'^getPg/', "getPg", name = 'getPg'),
		url(r'^getPgs/', "getPgs", name = "getPgs"),
)

thuysses/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('thuysses.views',
    # Examples:
    # url(r'^$', 'Thuysses.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', "index"),
	url(r'^get_page/(?P<annee>\w{1,9})/(?P<matiere>\w{1,50})/$', "get_page"),
    url(r'^third/(?P<matiere>\w{1,50})/$', "third"),
    url(r'^other/(?P<matiere>\w{1,50})/$', "other"),
    url(r'^creer_thuysse/$', "save_thuysse"),
    url(r'^action_change/', "action_change"),
    url(r'^download/(?P<id_dl>\d+)', "download"),
)

thuysses/models.py
# -*- coding: utf8 -*-
from django.db import models
import os

from thuysses.matieres import type_matiere, nom_annee, choix_matieres, choix_ss_matieres

def get_path (instance, filename):
	""" Function doc """
	path = os.path.join(os.path.split(instance.fichier.path)[0])
	try:
		path = os.path.join(path, "data", instance.annee, instance.matiere, instance.sous_matiere, instance.genre)
		os.mkdir(path)
	except os.error:
		pass
	return os.path.join(path, filename)
	

class Thuysse(models.Model):
	annee = models.CharField(max_length = 32, choices = nom_annee, verbose_name = "Année")
	matiere = models.CharField(max_length = 32, choices = choix_matieres, verbose_name = "Matière")
	sous_matiere = models.CharField(max_length = 32, choices = choix_ss_matieres, verbose_name = "Sous matière", blank = True)
	genre = models.CharField(max_length = 32, choices = type_matiere, verbose_name = "Genre")
	date_DL =  models.DateTimeField(auto_now_add=True, auto_now=False)
	name = models.CharField(max_length = 255, verbose_name = "Nom de la thuysse")
	auteur = models.CharField(max_length = 32)
	commentaire = models.TextField(blank = True)
	fichier = models.FileField(upload_to =get_path)
	DL_Thuysse = models.IntegerField(default = 0)
	publisher = models.ForeignKey("users.Client")

thuysses/forms.py
from django import forms
from thuysses.models import Thuysse

class ThuysseForm(forms.ModelForm):
	class Meta:
		model = Thuysse
		exclude = ["DL_Thuysse", "publisher"]
		widgets = {
			"annee" : forms.Select(attrs = {'onchange' : 'annee_change();'}),
			"matiere" : forms.Select(attrs = {'onchange' : 'matiere_change();'}),
			"sous_matiere" : forms.Select(attrs = {'onchange' : 'sous_matiere_change();'}),
			}

thuysses/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from thuysses.forms import ThuysseForm
from thuysses.models import Thuysse
import json
from users.models import Client
from django.db.models import Count

from thuysses.matieres import matieres as mats
from thuysses.matieres import choix_matieres, choix_ss_matieres, type_matiere

# Create your views here.

@login_required
def index (request):
	""" Function doc """
	thuysses_plus_DL = Thuysse.objects.all().order_by('DL_Thuysse').reverse()[:10]
	name_last_thuysse = Thuysse.objects.all().order_by('date_DL').reverse()[:10]
	thuysseurs = Client.objects.annotate(num_Thuysse=Count('thuysse'))[:10]
	return render(request, 'thuysses/index.html', {'thuysses_plus_DL' : thuysses_plus_DL, 'name_last_thuysse' : name_last_thuysse, 'thuysseurs' : thuysseurs})

@login_required
def get_page(request, annee = None, matiere = None):
	if annee == None:
		return redirect(index, request)
	ss_mat = []
	try:
		ss_mat = mats[annee][matiere]
	except KeyError:
		return redirect(index, request)
	dico = {}
	if not len(ss_mat):
		for i in type_matiere:
			dico[i[0]] = Thuysse.objects.filter(annee=annee, matiere=matiere, genre=i[0])
	for i in ss_mat:
		dico[i] = {}
		for j in type_matiere:
			dico[i][j[0]] = Thuysse.objects.filter(annee=annee, matiere=matiere,
												genre=j[0], sous_matiere=i)
	return render(request, 'thuysses/matiere_page.html', {'annee' : annee, 'matiere' : matiere, 'dico' : dico, 'ss_mat' : len(ss_mat) != 0})

@login_required
def third (request, matiere = None):
	""" Function doc """
	return index(request)
	
@login_required
def other (request, matiere = None):
	""" Function doc """
	return index(request)

@login_required
def action_change(request):
	""" Function doc """
	action_list = []
	annee = request.GET.get("annee")
	annee = str(annee)
	if annee in mats:
		choices = [i for i in choix_matieres if i[0] == '' or i[0] in mats[annee]]
	else:
		choices = []
		matiere = str(request.GET.get("matiere"))
		try:
			annee = ''
			for i in mats:
				j = mats[i]
				if matiere in j:
					annee = i
					break
			if annee == '':
				raise KeyError
			choices = [i for i in choix_ss_matieres if i[0] == '' or i[0] in mats[annee][matiere]]
		except KeyError:
			choices = []
	if len(choices) == 1 and choices[0][0] == '':
		choices = []
	j = json.dumps(choices)
	return HttpResponse(j, content_type = 'application/javascript')

@login_required
def save_thuysse (request):
	""" Function doc"""
	envoi = False
	if request.method == 'POST':
		form = ThuysseForm(request.POST.copy(), request.FILES)
		if form.is_valid():
			form = form.save(commit = False)
			gadz = Client.objects.get(username = request.user.username)
			form.publisher = gadz
			form.save()
			form = ThuysseForm()
			envoi = True
	else:
		form = ThuysseForm()
	return render(request, 'thuysses/creer_thuysse.html', {'form' : form, 'envoi' : envoi})		

@login_required
def download (request, id_dl):
	""" Function doc """
	obj = get_object_or_404(Thuysse, id = id_dl)
	return HttpResponse(obj.name)

templates/thuysses/base.html
{% extends "base.html" %}
{% load static %}

{% block bodystyle %}style = "background-color: #06002E;"{% endblock %}

{% block body %}
<style>
	@font-face {
    font-family: 'old';
    src: url("{% static 'fonts/old.eot' %}") format('eot'),
         url("{% static 'fonts/old.woff' %}") format('woff'),
         url("{% static 'fonts/old.truetype' %}") format('truetype'),
         url("{% static 'fonts/old.svg' %}") format('svg');
}
</style>
	<div class = "ui grid" style = "background-color: #06002E;">
		{% include "thuysses/navbar.html" %}
		<div class = "ui twelve wide column">
			{% block body2 %}
			{% endblock %}
			<div class = "ui divider inverted section"></div>
			<div style = "text-align : center; color : white;">
				<a class = "ui link" href="{% url 'thuysses.views.save_thuysse' %}"><p>Ajouter une nouvelle thuysse</p><img src="{% static 'images/mes_doc.png' %}"></a>
			</div>
		</div>
	</div>
{% endblock %}
{% block footer %}
	<script>
		$('.ui.accordion').accordion();
	</script>
	<script src = '{% static "javascript/action_change.js" %}'></script>
{% endblock %}

templates/thuysses/creer_thuysse.html
{% extends "thuysses/base.html" %}

{% block body2 %}

{% if envoi %}
	<h2 class = "ui header inverted">Votre thuysse a bien été envoyée !</h2>
{% endif %}

<h2 class = "ui header inverted"style= "font-family: 'old'">Envoyer une nouvelle thuysse</h2>

<form action="{% url 'thuysses.views.save_thuysse' %}" method="post" enctype = "multipart/form-data" style = "color: white;">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer"/>
</form>

{% endblock %} 

templates/thuysses/index.html
{% extends "thuysses/base.html" %}

{% block body2 %}
<h1 class = "ui inverted center aligned header" style = "font-family: 'old';"> Sal'ss</h1>
<h4 class = "ui inverted header"><br>Tu thuysses ou tu thuysses pas?<br>Si certains liens te semblent inaccessibles ou si tu trouves
que certaines rubriques manquent de thuysses, rop'ss un zident via l'email de la boquette:   thuysses.kin@gmail.com<br>Bon coürage à toüs!!<br> Z'merss
aux nombreux PG qui alimentent le site</h4>
<h4 class = "ui inverted header">Les Zidents Thuysses 213:<br><br>Silmaril 111<br>Azerty 118-163</h4>
<div class = "ui divider inverted section"></div>
<div class = "ui three column grid">
	<div class = "column">
		<div class = "ui center aligned segment"style="background-color : rgba(0,0,0,0);border-style : double;border-color : rgba(255,255,255,0.15)">
			<h3 class = "ui header inverted"style= "font-family: 'old';border-style : solid;border-color : rgba(255,255,255,0.15); border-width : thin">Nouvelles Thuysses</h3>
			<table class="ui basic table inverted"style= "background-color: rgba(0, 0, 0, 0)!important; border-style: solid; border-color: rgba(255, 255, 255, 0.15); border-width: thin;">
				{% for i in name_last_thuysse %}
				<tr>
					<td><a target = "_blank" title = "Envoyée par {{ i.publisher.username }}, créée par {{ i.auteur }}" style="color: rgba(255, 255, 255, 0.75);" href = "{% url 'thuysses.views.download' i.id %}">{{ i.name }}</a></td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	<div class = "column">
		<div class = "ui segment center aligned" style="background-color : rgba(0,0,0,0);border-style : double;border-color : rgba(255,255,255,0.15)">
			<h3 class = "ui header inverted" style= "font-family: 'old';border-style : solid;border-color : rgba(255,255,255,0.15); border-width : thin">Thuysseurs foüs</h3>
			<table class = "ui basic table inverted" style = "background-color: rgba(0, 0, 0, 0)!important; border-style: solid; border-color: rgba(255, 255, 255, 0.15); border-width: thin;">
				<thead>
					<tr>
						<th>Thuysseur</th>
						<th>Thuysses</th>
					</tr>
				</thead>
				<tbody>
					{% for i in thuysseurs %}
					{% if i.thuysse_set.count %}
						<tr>
							<td>{{ i.username }}</td>
							<td>{{ i.thuysse_set.count }}</td>
						</tr>
					{% endif %}
					{% endfor %}	
				</tbody>	
			</table>
		</div>
	</div>
	<div class = "column">
		<div class = "ui segment center aligned"style="background-color : rgba(0,0,0,0);border-style : double;border-color : rgba(255,255,255,0.15)">
			<h3 class = "ui header inverted"style= "font-family: 'old';border-style : solid;border-color : rgba(255,255,255,0.15); border-width : thin">Top 10 des thuysses</h3>
			<table class="ui basic table inverted" style = "background-color: rgba(0, 0, 0, 0)!important; border-style: solid; border-color: rgba(255, 255, 255, 0.15); border-width: thin;">
				<tr>
					<td>Thuysse</td>
					<td>DL</td>
				</tr>
				{% for i in thuysses_plus_DL %}
					<tr>
						<td><a target = "_blank" title = "Envoyée par {{ i.publisher.username }}, créée par {{ i.auteur }}" style="color: rgba(255, 255, 255, 0.75);" href = "#">{{ i.name }}</a></td>
						<td>{{ i.DL_Thuysse}}</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/thuysses/matiere_page.html
{% extends "thuysses/base.html" %}

{% block body2 %}
<script>
	$('.ui.accordion').accordion("open", {{ annee }} - 1);
</script>
<h1 class = "ui header" style = "font-family: 'old';text-align: center; text-decoration: underline; color : white;">{{ matiere|title }}</h1>
<div class = "ui basic accordion" style = "position: relative; left: 2em;">
	{% if not ss_mat %} 
	{% for value, content in dico.items %}
		{% if content %}
	<div class = "title">
		<i class = "icon dropdown" style = " color : white;"></i>
		<font color = "white">{{ value }}</font>
	</div>
	<div class = "content">
		<div class = "ui bulleted link list" style = "position: relative; left: 5em;">
			{% for i in content %}
			<a class = "link item" href = "{% url 'thuysses.views.download' i.id %}" style="color: rgba(255, 255, 255, 0.75);">
				{{ i.name }}
			</a>
			{% endfor %}
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% else %}
	{% for sous_mat,d in dico.items%}
	<h4 class = "ui header center aligned segment inverted"style=" background-color : rgba(0,0,0,0)!important;border-style : solid;border-width:1px;border-color : rgba(255,255,255,0.15)">{{sous_mat|title}}</h4>
	{% for value, content in d.items %}
		{% if content %}
	<div class = "title">
		<i class = "icon dropdown" style = " color : white;"></i>
		<font color = "white">{{ value }}</font>
	</div>
	<div class = "content">
		<div class = "ui bulleted link list" style = "position: relative; left: 5em;">
			{% for i in content %}
			<a class = "link item" href = "{% url 'thuysses.views.download' i.id %}" style="color: rgba(255, 255, 255, 0.75);">
				{{ i.name }}
			</a>
			{% endfor %}
		</div>
	</div>
	{% endif %}
	{% endfor %}
	{% endfor %}
	{% endif %}
</div>
{% endblock %}

templates/thuysses/navbar.html
{% load static %}
<div class = "ui three wide column" style = "background: linear-gradient(to bottom, rgba(22, 35, 124, 1), #06002E);">
<div class = "ui inverted labeled icon vertical accordion menu" style = "background: linear-gradient(to bottom, rgba(22, 35, 124, 1), #06002E);">
	<a class = "item" href = "{% url 'thuysses.views.index' %}" style = "font-family: 'old'; font-size : 30px"><img src = "{% static 'images/sonic.png' %}" style = "height: 100px;"/>Thuysse KIN</a>
	<div class = "item">
		<div class = "title" style = "text-align: left;">
			<i class = "dropdown icon"></i>
			<h4 style = "color: rgba(255, 255, 255, 0.8);">Première année</h4>
		</div>
		<div class = "content">
			<div class = "menu">
			{% for i in first %}
				<a class = "item" href = "{% url 'thuysses.views.get_page' 'first' i %}">{{ i }}</a>
			{% endfor %}
			</div>
		</div>
	</div>
	<div class = "item">
		<div class = "title" style = "text-align: left;">
			<i class = "dropdown icon"></i>
			<h4 style = "color: rgba(255, 255, 255, 0.8);">Deuxième année GM</h4>
		</div>
		<div class = "content">
			<div class = "menu">
			{% for i in secondGM %}
				<a class = "item" href = "{% url 'thuysses.views.get_page' 'secondGM' i %}">{{ i }}</a>
			{% endfor %}
			</div>
		</div>
	</div>
	<div class = "item">
		<div class = "title" style = "text-align: left;">
			<i class = "dropdown icon"></i>
			<h4 style = "color: rgba(255, 255, 255, 0.8);">Deuxième année GI</h4>
		</div>
		<div class = "content">
			<div class = "menu">
			{% for i in secondGI %}
				<a class = "item" href = "{% url 'thuysses.views.get_page' 'secondGI' i %}">{{ i }}</a>
			{% endfor %}	
			</div>
		</div>
	</div>
	<div class = "item">	
		<div class = "title" style = "text-align: left;">
			<i class = "dropdown icon"></i>
			<h4 style = "color: rgba(255, 255, 255, 0.8);">Troisième année</h4>
		</div>
		<div class = "content">
			<div class = "menu">
			{% for i in third %}
				<a class = "item" href = "{% url 'thuysses.views.third' i %}">{{ i }}</a>
			{% endfor %}	
			</div>
		</div>
	</div>
	<div class = "item">	
		<div class = "title" style = "text-align: left;">
			<i class = "dropdown icon"></i>
			<h4 style = "color: rgba(255, 255, 255, 0.8);">Autres</h4>
		</div>
		<div class = "content">
			<div class = "menu">
			{% for i in other %}
				<a class = "item" href = "{% url 'thuysses.views.other' i %}">{{ i }}</a>
			{% endfor %}	
			</div>
		</div>
	</div>
</div>
</div>

templates/thuysses/navbar2.html
<div class = "ui inverted purple fixed secondary
 menu">
	<a class = "item">
		<i class = "home icon"></i>Intra
	</a>
	<div class = "right menu">
		<div class = "item">
			<div class = "ui icon input">
				<input type = "text" placeholder = "Rechercher...">
				<i class = "search link icon"></i>
			</div>
		</div>	
		<a class = "item">Admin</a>
	</div>
</div>